name: Responsive One
favicon: null
layout_spectrum: 0.5075061810202897
typography_spectrum: 0.17757237795740366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030511'
    - '#434343'
    - '#d2d1d1'
    - '#858585'
    - '#fdfdfd'
  brandStrength: 0.6641239139717072
  lightness: 0.19618241116404533
  saturation: 0.34869562229141593
  rhythmicContrast: 0.004052622709423304
purpose: []
