name: Responsive One
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030511'
    - '#434343'
    - '#d2d1d1'
    - '#858585'
    - '#fdfdfd'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.004052622709423304
purpose: []
